services:
  django:
    build:
      context: .
      dockerfile: Backend/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend/api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  nuxt:
    build:
      context: .
      dockerfile: Manager/Dockerfile
    command: pnpm start
    volumes:
      - ./Manager:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - django
