services:
  django:
    build:
      context: .
      dockerfile: Backend/api/Dockerfile
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Backend/api:/app
  nuxt:
    build:
      context: .
      dockerfile: Manager/Dockerfile
    command: pnpm start
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - django
    volumes:
      - ./Manager:/app
