# Generated by Django 5.0.6 on 2024-08-01 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employees_e_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='is_manager',
            new_name='is_Manager',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='line_manager',
            new_name='line_Manager',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='surname',
        ),
        migrations.AddField(
            model_name='employees',
            name='u_id',
            field=models.ForeignKey(default=99999999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
