# Generated by Django 5.0.6 on 2024-08-01 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employees_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='hired_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, default='image.jpeg', upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, default='Employee', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
