# Generated by Django 5.0.6 on 2024-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employees_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birth_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hired_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(default='Employee', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
