# Generated by Django 5.0.6 on 2024-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_manager_e_id_manager_e_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='e_identifier',
        ),
        migrations.AddField(
            model_name='manager',
            name='e_id',
            field=models.BigIntegerField(auto_created=True, default=1, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='e_id',
            field=models.BigIntegerField(auto_created=True, unique=True, verbose_name='ID'),
        ),
    ]
