# Generated by Django 5.0.6 on 2024-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_manager_e_identifier_manager_e_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='image',
        ),
        migrations.AddField(
            model_name='employees',
            name='gravatar_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
